### PR TITLE
Fixed docker facts to check for active swarm clusters before running docker swarm sub-commands.

### LINKED ISSUE #702: Why module want connect to Swarm API?
## Describe the Bug
When I run Puppet on the machine, I receive many messages in syslog:
```
...
Dec 16 17:16:50 test_server dockerd[952]: time="2020-12-16T17:16:50.820167497Z" level=error msg="Error getting swarm: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
Dec 16 17:16:50 test_server dockerd[952]: time="2020-12-16T17:16:50.820246124Z" level=error msg="Handler for GET /v1.41/swarm returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again."
...
```

In debug mode:
```
...
Debug: Facter: executing command: /usr/bin/sh -c /usr/bin/docker swarm join-token manager -q
Debug: Facter: Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
Debug: Facter: executing command: /usr/bin/sh -c /usr/bin/docker swarm join-token worker -q
Debug: Facter: Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
...
```

## Expected Behavior
I don't want to receive this messages to syslog

## Steps to Reproduce
1. Just install Docker via module, without any additional parameters

## Environment
 - Puppet 5.5.10
 - Debian 10
 - Docker 20.10

What I need to do, when I don't want to use Swarm Mode? Is it bug or feature? Is there any flags/parameters for skip checking Swarm mode?

Thank you in advance :)

### PR DESCRIPTION
**Pull request by nmaludy**
Closes #702

Previously the docker facts would run `docker swarm` commands without knowing if the node was a member of a swarm cluster. This generated errors in `/var/log/messages` every time facts were collected.

The fix is to check if the node is a member of an active swarm cluster before trying to run the swarm commands. Inspired by: https://stackoverflow.com/questions/43053013/how-do-i-check-that-a-docker-host-is-in-swarm-mode

### CODE REVIEW

File: lib/facter/docker.rb [hunk 1]
```diff
@@ -91,14 +102,26 @@ def interfaces
...
+        end
+      rescue JSON::ParserError
+        nil
+      end
     end
     val
   end
 end
 
+
```
Comment (chelnak) [inline lib/facter/docker.rb:124]:
```suggestion
```

**Review by chelnak — CHANGES_REQUESTED** [review]
This looks fine. Can you remove the extra new line that has been added in docker.rb:124 please? 

Then we can get this one merged.

**Comment by nmaludy** [comment]
@chelnak Done.

**Review by chelnak — APPROVED** [review]

File: lib/facter/docker.rb [hunk 2]
```diff
@@ -80,9 +80,20 @@ def interfaces
 Facter.add(:docker_worker_join_token) do
   setcode do
     if Facter::Core::Execution.which('docker')
```
Comment (bastelfreak) [inline lib/facter/docker.rb:82]: I think we could make the facts more readable if we confine them on the docker binary, instead of this if:
```
confine { Facter::Core::Execution.which('docker') }
```

File: lib/facter/docker.rb (hunk 1 above)
Comment (chelnak) [reply lib/facter/docker.rb:124]: Looks like this came back after your latest merge

File: lib/facter/docker.rb (hunk 2 above)
Comment (nmaludy) [reply lib/facter/docker.rb]: Done

**Review by bastelfreak — APPROVED** [review]

**Review by chelnak — APPROVED** [review]

**Comment by chelnak** [comment]
Thank you for your contribution 🙏 👍
